name: parcial_3
services:
  api: 
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - 8081:8080
    depends_on:
      - db
  
  db:
    build: ./db
    env_file:
      - ./db/.env
    volumes:
      - pgdata:/var/lib/postgresql/data  
    ports:
      - "5432:5432"

volumes:
  pgdata: {}